# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TimeCapsule' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TimeCapsule
 pod 'Alamofire'
 pod 'KakaoSDKCommon'
 pod 'KakaoSDKAuth'
 pod 'KakaoSDKUser'

  target 'TimeCapsuleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TimeCapsuleUITests' do
    # Pods for testing
  end

end
